name: ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  flutter_map: ^6.0.0
  flutter_map_heatmap: any # or the latest version on Pub
  latlong2: ^0.9.0
  socket_io_client: ^2.0.0
  url_launcher: ^6.1.14
  image_picker: ^0.8.4+6
  path_provider: ^2.0.11
  flutter_sound: ^9.6.0
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/back1.png

